### ISSUE TITLE
Make a Logo for Metapub

### ISSUE THREAD

**Issue by nthmost** [metapub/metapub#15]
Metapub needs a logo!  Right?!  Yes.

**Comment by joofio** [comment]
Hi, I can help with this! Any ideas so far?

**Comment by nthmost** [comment]
Hi @joofio !  open to all kinds of ideas at this point!

**Comment by joofio** [comment]
I will make a couple of options are post them here.

**Comment by rayking99** [comment]
![IMG_0130](https://user-images.githubusercontent.com/85595170/125152555-8b16ce80-e190-11eb-9c98-da8f8dc09dba.PNG)
I thought I'd add one, as I really like this package - not too sure if it's what you're after, but I thought it combined some nice ideas.

**Comment by rayking99** [comment]
![IMG_0134](https://user-images.githubusercontent.com/85595170/125152831-df22b280-e192-11eb-88a1-3dd95f46a4cd.PNG)
![IMG_0133](https://user-images.githubusercontent.com/85595170/125152834-e0ec7600-e192-11eb-90e5-884741c52931.PNG)
And a couple more slightly improved / different for the sake of variety.

**Comment by rayking99** [comment]
![IMG_0138](https://user-images.githubusercontent.com/85595170/125155436-37fa4700-e1a3-11eb-9164-15c1ed5822c4.jpg)
![Uploading IMG_0139.PNG…]()

**Comment by rayking99** [comment]
![IMG_0138](https://user-images.githubusercontent.com/85595170/125155445-4a748080-e1a3-11eb-9b39-ec1e6029266c.jpg)
![IMG_0139](https://user-images.githubusercontent.com/85595170/125155449-4d6f7100-e1a3-11eb-8140-bf97c5a63800.PNG)

**Comment by rayking99** [comment]
![IMG_0140](https://user-images.githubusercontent.com/85595170/125155730-25810d00-e1a5-11eb-8f38-452e83f60840.jpg)

**Comment by rayking99** [comment]
![IMG_0141](https://user-images.githubusercontent.com/85595170/125156113-29ae2a00-e1a7-11eb-957e-dfc71811c828.jpg)

**Comment by rayking99** [comment]
![IMG_0142](https://user-images.githubusercontent.com/85595170/125156197-a6d99f00-e1a7-11eb-827a-0ff9a625bea1.jpg)

**Comment by rayking99** [comment]
looks like an eye, a person and a caduceus

**Comment by rayking99** [comment]
happy to send some more if you want iterations.

**Comment by rayking99** [comment]
![IMG_0144](https://user-images.githubusercontent.com/85595170/125161355-2aee4f80-e1c5-11eb-9553-7ad01ad80c2d.jpg)

**Comment by rayking99** [comment]
![io](https://user-images.githubusercontent.com/85595170/125179329-1182ed00-e231-11eb-9242-9670ea2f32d6.png)
![pyu](https://user-images.githubusercontent.com/85595170/125179331-147ddd80-e231-11eb-8283-428199c170c5.jpg)
some others with pubmed-ish colours - moving into a dna kind of look too.

**Comment by joofio** [comment]
Hi sorry! Life kinda got in the way.

The last one with no drop shadow would be better. Then we need to create png, black and white and vector no?

For me the second one with a magnifying glass in the middle would be cool since it adds for the lookup.

**Comment by rayking99** [comment]
I've put them all in there -- https://www.dropbox.com/sh/0a0hay2x9qpy5dk/AAB2-ccFzRNQoOGMEcLy9x4-a?dl=0

Magnifying glass looks pretty good. 

Happy to do some more work on them - just let me know what you need.

**Comment by nthmost** [comment]
Hey guys, thanks for posting some options.  I know it's been a long while since I attended to this project (lots of life issues).  I really appreciate the creative work and I'll audition a few of these ideas with a colleague on Monday.

Thanks again.

**Comment by nthmost** [comment]
Going with a logo from another source.  Thanks again for your contributions, they were good motivation for getting back on track with this project!
