### ISSUE TITLE
Abstracts of articles truncate when there is an HTML tag in there.

### ISSUE THREAD

**Issue by narayanacharya6** [metapub/metapub#22]
Notice the same (or similar) issue with Article titles (#16 ) was closed. You can try out for this article with id 28661438 to reproduce where the abstract truncates at the first italic 'p' in the content. I can add more details if required.

**Comment by nthmost** [comment]
Hi @narayanacharya6 , thanks for the bug report.  Yeah it sounds like the same kind of issue.

The best thing that would help is just more pubmed ID numbers that have this problem, as you find them.  I will take a look at this bug as soon as I can, unless someone else gets to it first.  :) 

Thanks again!

**Comment by jvansan** [comment]
I took a look at this and it seems that the abstract parser doesn't use the same method at the title parse from #16, but we can use the same approach to fix this issue. I'll submit a PR.
