### ISSUE TITLE
How to get the citations count for each article

### ISSUE THREAD

**Issue by MathewKevin** [metapub/metapub#40]
Is there a way to get the cited by count for each article, I could see there is a method named citation under PubMedFetcher, but it generates a string. I would like to get the count (how many people have cited that article). Any help is appreciated. Thanks

```
article = metapub.PubMedFetcher().article_by_pmid('35403186')
article.citation
```

**Comment by nthmost** [comment]
Hi @MathewKevin -- 

the PubMedArticle object reports on exactly the items that are provided from the PubMedArticle XML object from NCBI, and they don't store the citation *count* on that data object (you can have a look at the [Medline XML spec](https://www.nlm.nih.gov/bsd/licensee/data_elements_doc.html) here).

You have to acquire that information in sort of a roundabout fashion.  I'm just getting back from a long sabbatical and need to attend to a few things, but I'll try to post a code snippet that shows how to do it as soon as I can.

Check out the demo/ directory in this repo too -- I seem to recall writing that snippet before for myself.

Thanks for your patience!

**Comment by MathewKevin** [comment]
@nthmost Thank you so much for your response, I found a package named pmidcite which gives the citation count, it also provides RelativeCitationRatio and FieldCitationRate which are quite useful for my project. I was using metapub to get the abstract and other key features. I'm figuring out to use multiprocessing since I have more data to extract, if you know any technique in speeding up the search, please do share, thanks again.

**Comment by nthmost** [comment]
Thanks for the tip about pmidcite, @MathewKevin -- maybe metapub can learn some functionality from it.

In terms of parallelizing: I guess that depends on what you're trying to speed up and why it seems slow right now.  If you're restricted by network requests, you could either register an NCBI key which would get you up to 10 requests per second, or (much faster but a little more complicated), you could download the whole pubmed database and run DB queries directly on a local copy. 

Let me know what your use case is and i'll see if i can suggest anything.

**Comment by MathewKevin** [comment]
I'm building a Biomedical Scientific Article Recommender System. I'm using ElasticSearch to store the data and retrieve them since it is faster as well as relevance. I searched for the keyword "protein" and got around 8 million records, I started downloading them, but it looks like it would take months despite having NCBI key. So I was looking for some technique to speed up the process of downloading the data. Only then I would be able to start building the recommender system.

**Comment by nthmost** [comment]
@MathewKevin Yeah for that use case I would *definitely* recommend downloading the whole pubmed / MEDLINE database.

My colleague Dr. Andy McMurry (and my former team lead) created a download-and-extract-to-MySQL utility called medgen-mysql that you could check out.  I used it in a subsequent project called text2gene, so here it is in that context:

https://github.com/text2gene/medgen-mysql
