### ISSUE TITLE
Metapub FindIt Issue: Broken Embargo Handling

### ISSUE THREAD

**Issue by hassaanQadir** [metapub/metapub#48]
## Metapub FindIt Issue: Broken Embargo Handling

Hey! I’ve been using **metapub** for a few months now, and it’s been a complete lifesaver! Really essential library for my work. However, **FindIt** seems to be broken as of maybe a few days ago.

### Issue Description

When using **FindIt** to fetch URLs for PDFs of certain PMIDs, it worked flawlessly until about a week ago. But now, it returns errors instead of URLs for these PMIDs. This issue seems to be related to how FindIt handles **embargoes** on articles, as all the problematic PMIDs report being under embargo, despite those embargoes having ended years ago.

### Steps to Reproduce

Here's the Python code snippet used to reproduce the issue:

```python
from metapub import FindIt

# Example PMIDs
pmids = ['24959857', '20147967', '29099059']

for pmid in pmids:
    src = FindIt(pmid)
    if src.url == None:
        print(f"PMID: {pmid} returns {src.reason}")

```

### Affected PMIDs and Errors

- **PMID: 24959857** returns `PAYWALL: pmc article in embargo until 2014-06-24`
- **PMID: 20147967** returns `PAYWALL: pmc article in embargo until 2011-02-16`
- **PMID: 29099059** returns `PAYWALL: pmc article in embargo until 2017-11-01`

### Possible Causes

The issue might be related to NCBI's implementation of the datasets API over the e-utilities API, but I haven't observed any changes to either API or to metapub itself within the last week that could have caused this issue.

### Request for Insight

I’ll do my own tinkering around to try and identify the issue, but if anyone has any insight or has encountered a similar issue, please let me know! Thanks!

**Comment by nthmost** [comment]
Hi Hassan, sorry it's taken me a while to reply to this!  Appreciate the report.

It looks like some of the base libraries under metapub have changed, so I'll fix those up first and then see if I can reproduce.

Thanks for your patience.

**Comment by nthmost** [comment]
Hi @hassaanQadir thanks again for your patience on this one.  I've reproduced the problem myself and will be working on a fix shortly.

**Comment by nthmost** [comment]
OK, I figured this issue out and I'm testing out the solution.  Watch for a minor version bump to `metapub 0.5.8`

Thanks for your patience!
