### ISSUE TITLE
Error parsing response object from NCBI

### ISSUE THREAD

**Issue by FurkanBeyazit** [metapub/metapub#67]
### Discussed in https://github.com/metapub/metapub/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **FurkanBeyazit** October 15, 2024</sup>
Hello we are using PubMedFetcher to work with articles. Our code were fine. Since last week we get this error "EutilsNCBIError: Error parsing response object from NCBI: Bad Request (400): Unknown Error". I have contacted with Pubmed support they have told me there are no issues. Actually w/o API it worked same and API calls seemed fine cause I can get the pmids but can't get the PubMedFetcher().article_by_pmid(pmid).journal or else. Except me no one seemed to have this problem so tried with another computer with new env. did not work there aswell. Help me out please. Thank you</div>

**Comment by nthmost** [comment]
Thanks for your report, sorry I'm just seeing this now.

Can you supply me with a quick script to reproduce the error?  That would be helpful.  

I'll try to reproduce myself in the meantime.

**Comment by FurkanBeyazit** [comment]
Hey, contacted NCBI , they said there was a temporary API problem. Now all looking good
